# Sandbox config example

# global parameters
project_name: 'demo-sandbox'
experiment_name: 'demo-sandbox-run0'              # for wandb tracer name
hpo_config: null                                  # path to a configuration file when using auto-HPO tool.

# configs for each job, the jobs will be executed according to the order in the list
probe_job_configs:
  - hooker: 'ProbeViaAnalyserHooker'
    res_name: 'analysis_ori_data'
    dj_configs: 'configs/demo/process.yaml'
    other_configs:
  # - hooker: 'ProbeViaModelInferHooker'
  #   res_name: 'analysis_ori_model'
  #   dj_configs:
  #     dataset_path: './demos/data/demo-dataset.jsonl'
  #     export_path: './outputs/demo-sandbox/demo-sandbox.jsonl'
  #     data_probe_algo: 'uniform'
  #     data_probe_ratio: 0.5
  #     other_configs:
  #       (...model configs)

refine_recipe_job_configs:
  - hooker: 'RefineRecipeViaKSigmaHooker'
    res_name: 'analysis_ori_data'
    dj_configs: 'configs/demo/process.yaml'
    other_configs:
      path_k_sigma_recipe: './outputs/demo-process/k_sigma_new_recipe.yaml'
  # - hooker: 'RefineRecipeViaModelFeedbackHooker'
  #   res_name:
  #   dj_configs:
  #   other_configs:
  #     (...model configs)

execution_job_configs:
  - hooker: 'ProcessDataHooker'
    res_name:
    dj_configs: 'configs/demo/process.yaml'
    other_configs:
  - hooker: 'TrainModelHooker'
    res_name:
    dj_configs:
    other_configs: 'configs/demo/sandbox/gpt3_extra_train_config.json'

evaluation_job_configs:
  - hooker: 'ProbeViaAnalyserHooker'
    res_name: 'analysis_processed_data'
    dj_configs: 'configs/demo/process.yaml'
    other_configs:
  # - hooker: 'ProbeViaModelInferHooker'
  #   res_name: 'analysis_trained_model'
  #   dj_configs:
  #     dataset_path: './demos/data/demo-dataset.jsonl'
  #     export_path: './outputs/demo-sandbox/demo-sandbox.jsonl'
  #     data_probe_algo: 'uniform'
  #     data_probe_ratio: 0.5
  #     other_configs:
  #       (...model configs)
  - hooker: 'EvaluateDataHooker'
    res_name: 'eval_data'
    dj_configs:
    other_configs: 'configs/demo/sandbox/gpt3_data_quality_eval_config.yaml'
  # - hooker: 'EvaluateModelHooker'
  #   res_name: 'eval_model'
  #   dj_configs:
  #   other_configs:
  #     (...model configs)
