# Sandbox config example for dataset

# global parameters
project_name: 'demo-sandbox'
dataset_path: './demos/data/demo-dataset.jsonl'  # path to your dataset directory or file
np: 4  # number of subprocess to process your dataset

export_path: './outputs/demo-sandbox-data-partition/demo-sandbox.jsonl'

# only for data analysis
# percentiles to analyse the dataset distribution
percentiles: [0.333, 0.666]
# whether to export the original dataset with stats. If you only need the stats of the dataset, setting it to false could speed up the exporting.
export_original_dataset: true
# whether to store all stats result into one file
save_stats_in_one_file: true

# sandbox configs
# choose one data process for sandbox. Should be one of ["data_juicer_run", "data_sample", "divide_by_percentiles"]. The "data_juicer_run" for running setting ops in process, "data_sample" for data sampling, "divide_by_percentiles" for data partitioning.
data_process_type: 'divide_by_percentiles'
# fix data num for each partition
fix_data_num: 4

# process schedule
# a list of several process operators with their arguments
process:
  - language_id_score_filter:
      lang: 'zh'
      min_score: 0.5
